// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBraR6mvDajoq-lz5GbJOGnNCB23QWHo2g',
    appId: '1:926313390253:web:64fed2b9057e5e4fcd2624',
    messagingSenderId: '926313390253',
    projectId: 'plantify-5944d',
    authDomain: 'plantify-5944d.firebaseapp.com',
    storageBucket: 'plantify-5944d.appspot.com',
    measurementId: 'G-KPDZDB7M6B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAtDnZRLO9zUFj4dg5FyZMQhQ54zz3JR8U',
    appId: '1:926313390253:android:cb30f0ff50355276cd2624',
    messagingSenderId: '926313390253',
    projectId: 'plantify-5944d',
    storageBucket: 'plantify-5944d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDQfF_Fv-r0MllUnHhHVgu6tAWWMGd1Usc',
    appId: '1:926313390253:ios:85cc8c0c78697b87cd2624',
    messagingSenderId: '926313390253',
    projectId: 'plantify-5944d',
    storageBucket: 'plantify-5944d.appspot.com',
    iosBundleId: 'com.NexGen.farmerEcommerce',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDQfF_Fv-r0MllUnHhHVgu6tAWWMGd1Usc',
    appId: '1:926313390253:ios:85cc8c0c78697b87cd2624',
    messagingSenderId: '926313390253',
    projectId: 'plantify-5944d',
    storageBucket: 'plantify-5944d.appspot.com',
    iosBundleId: 'com.NexGen.farmerEcommerce',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBraR6mvDajoq-lz5GbJOGnNCB23QWHo2g',
    appId: '1:926313390253:web:0b742ce2a3f8b6b2cd2624',
    messagingSenderId: '926313390253',
    projectId: 'plantify-5944d',
    authDomain: 'plantify-5944d.firebaseapp.com',
    storageBucket: 'plantify-5944d.appspot.com',
    measurementId: 'G-KWBSSDMHPS',
  );
}
